# Generated by Django 3.1.3 on 2021-10-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naner', '0005_jogo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data_criado',
        ),
        migrations.AddField(
            model_name='jogo',
            name='data_criado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
